version: 2

sources:
  - name: tpc_h
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: region
      - name: nation
      - name: customer
      - name: orders
      - name: lineitem
      - name: supplier
      - name: part
      - name: partsupp
